"""patch_styles.py — Playwright dump 한 raw CSS의 blob URL을 정적 경로로 치환.

Step:
  1. ../../v2-stylesheets-raw.css (Playwright dump 결과) 읽기
  2. blob URL → byteLength → assets/<fname> size 매칭
  3. blob URL 부분을 ./assets/<fname>으로 치환
  4. ../styles.css 에 최종 저장 (extract_v2_assets.py가 만든 인라인 <style>은 일단 유지)

매핑 정보는 size unique임이 확인됨 (16개 폰트 모두 distinct size).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent  # v2/
RAW_CSS = Path(__file__).parent / "raw_styleSheets.css"  # _decode/로 옮겨둠
ASSETS_DIR = ROOT / "assets"
STYLES_OUT = ROOT / "styles.css"

# Playwright evaluate가 받은 byteLength → blob URL 매핑
# (위 evaluate 결과 그대로 옮김)
BLOB_BY_SIZE: dict[int, str] = {
    25960: "blob:http://localhost:8765/a8e1590f-ad12-4000-87cd-5dc7065d185f",
    18748: "blob:http://localhost:8765/7a1bf501-6df1-4649-9485-958da821bbff",
    11232: "blob:http://localhost:8765/0fe51cf0-0822-437d-8c1a-100b8582d5d5",
    18996: "blob:http://localhost:8765/08250ac2-3434-480a-9e84-3ea23f2088d3",
    10252: "blob:http://localhost:8765/c1cbc7c8-ac94-40d2-bab4-1f2dd7eb35bd",
    85068: "blob:http://localhost:8765/8f7a7871-5d8b-402f-ba7e-dfd787eabecd",
    48256: "blob:http://localhost:8765/c92d192f-7100-4ad6-adb8-34b0f7cc7313",
    2028:  "blob:http://localhost:8765/98811f1a-52f9-4356-a232-1f05fcffe45f",
    12108: "blob:http://localhost:8765/23fcc063-0844-4cfa-8d09-27c707bc7415",
    9004:  "blob:http://localhost:8765/378f35d7-d05d-4fc3-bccc-c618f936a5c2",
    7504:  "blob:http://localhost:8765/73e36dd9-7df1-4983-84d2-ba648e5e6483",
    15196: "blob:http://localhost:8765/f22e4289-e3c4-41b3-89d2-bb428ef49ac1",
    40404: "blob:http://localhost:8765/ca4d945d-dd5e-451a-bfd3-9a906112a77c",
    6712:  "blob:http://localhost:8765/d193f334-8ee1-43c8-9393-3f3cdbc8c524",
    18940: "blob:http://localhost:8765/77d7324b-63c5-451d-af60-9580d95f3dc6",
    22288: "blob:http://localhost:8765/990d279a-133e-46b3-af26-983bb173a666",
}


def main() -> int:
    if not RAW_CSS.exists():
        print(f"[ERR] raw css not found: {RAW_CSS}", file=sys.stderr)
        return 1

    raw = RAW_CSS.read_text(encoding="utf-8")
    print(f"[INFO] raw file: {len(raw):,} chars")
    # Playwright evaluate(filename) 결과는 JSON.stringify된 형태 — 즉
    # 양 끝의 따옴표 제거 + escape unescape 필요.
    if raw.startswith('"') and raw.endswith('"\n'):
        raw = raw[1:-2]  # strip leading " and trailing "\n
    elif raw.startswith('"') and raw.endswith('"'):
        raw = raw[1:-1]
    # JSON-style escape 복원
    css = (
        raw.replace("\\n", "\n")
        .replace('\\"', '"')
        .replace("\\\\", "\\")
    )
    print(f"[INFO] unescaped css: {len(css):,} chars")

    # assets 의 size → fname 인덱스
    size_to_fname: dict[int, str] = {}
    for f in ASSETS_DIR.iterdir():
        if f.suffix.lower() == ".woff2":
            size_to_fname[f.stat().st_size] = f.name
    print(f"[INFO] indexed {len(size_to_fname)} woff2 files by size")

    # blob URL → fname
    url_to_fname: dict[str, str] = {}
    for size, url in BLOB_BY_SIZE.items():
        fname = size_to_fname.get(size)
        if fname:
            url_to_fname[url] = fname
        else:
            print(f"[WARN] no asset of size {size} for {url}", file=sys.stderr)

    print(f"[INFO] mapped {len(url_to_fname)} blob URLs → fnames")

    # 치환
    patched = css
    replaced = 0
    for url, fname in url_to_fname.items():
        if url in patched:
            patched = patched.replace(url, f"./assets/{fname}")
            replaced += 1

    # 잔존 blob 검사
    remaining = re.findall(r"blob:[^\"')\s]+", patched)
    print(f"[INFO] replaced {replaced} URLs ; remaining blob refs: {len(remaining)}")
    if remaining:
        for r in remaining[:5]:
            print(f"  - leftover: {r}", file=sys.stderr)

    # 헤더 추가 후 저장 (기존 inline <style>은 styleSheets dump에 이미 포함됐을 가능성 높음)
    header = (
        "/* ============================================================\n"
        " * v2 styles.css\n"
        " * Source: Playwright styleSheets dump from standalone-original.html\n"
        " * Generated by modules/integration/v2/_decode/patch_styles.py\n"
        " * blob: URL → ./assets/<fname>.woff2 (size-matched, 1:1)\n"
        " * ============================================================ */\n\n"
    )
    STYLES_OUT.write_text(header + patched, encoding="utf-8")
    print(f"[INFO] wrote {STYLES_OUT} ({STYLES_OUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
