#!/usr/bin/env python
"""Claude → Codex 하네스 미러 생성기.

**정본은 Claude**: CLAUDE.md 와 .claude/skills/*/SKILL.md.
이 스크립트가 여기서 Codex용 미러를 결정적으로(deterministic) 생성한다:
  - CLAUDE.md                      → AGENTS.md
  - .claude/skills/<x>/SKILL.md    → .agents/skills/<x>/SKILL.md

(.codex/config.toml·.codex/agents/*.toml 은 Codex 네이티브 설정이라 대상 아님.)

사용:
  python scripts/sync_codex.py          # 미러 생성/갱신
  python scripts/sync_codex.py --check   # 미러가 정본과 일치하는지 검사 (CI용, 불일치 시 exit 1)

치환 규칙 (순서 중요):
  1. ".claude/skills" → ".agents/skills"   (스킬 경로가 먼저)
  2. ".claude"        → ".codex"
  3. "Claude Code"    → "Codex"
  4. 루트 "CLAUDE.md" → "AGENTS.md"        ( "/" 뒤 모듈 CLAUDE.md 는 실제 파일명이라 유지 )
  5. "Claude"         → "Codex"
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

BANNER = (
    "<!-- AUTO-GENERATED by scripts/sync_codex.py from CLAUDE.md / .claude/skills"
    " — 직접 수정 금지. Claude 정본을 고친 뒤 스크립트를 재실행할 것. -->"
)

_FRONTMATTER = re.compile(r"^(---\n.*?\n---\n)(.*)$", re.S)


def transform(text: str) -> str:
    text = text.replace(".claude/skills", ".agents/skills")
    text = text.replace(".claude", ".codex")
    text = text.replace("Claude Code", "Codex")
    text = re.sub(r"(?<!/)CLAUDE\.md", "AGENTS.md", text)
    text = text.replace("Claude", "Codex")
    return text


def with_banner(text: str) -> str:
    m = _FRONTMATTER.match(text)
    if m:
        return m.group(1) + BANNER + "\n\n" + m.group(2)
    return BANNER + "\n\n" + text


def _pairs():
    yield ROOT / "CLAUDE.md", ROOT / "AGENTS.md"
    skills_dir = ROOT / ".claude" / "skills"
    for skill in sorted(skills_dir.glob("*/SKILL.md")):
        rel = skill.relative_to(ROOT / ".claude" / "skills")
        yield skill, ROOT / ".agents" / "skills" / rel


def render(src: Path) -> str:
    return with_banner(transform(src.read_text(encoding="utf-8")))


def main(argv) -> int:
    check = "--check" in argv
    mismatches, written = [], []
    for src, dst in _pairs():
        if not src.exists():
            continue
        expected = render(src)
        current = dst.read_text(encoding="utf-8") if dst.exists() else None
        if check:
            if current != expected:
                mismatches.append(dst.relative_to(ROOT).as_posix())
        elif current != expected:
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_text(expected, encoding="utf-8")
            written.append(dst.relative_to(ROOT).as_posix())

    if check:
        if mismatches:
            print("DRIFT: Codex 미러가 정본과 다릅니다:")
            for m in mismatches:
                print("  -", m)
            print("해결: python scripts/sync_codex.py")
            return 1
        print("OK: Codex 미러가 정본과 일치합니다.")
        return 0

    if written:
        print("생성/갱신:")
        for w in written:
            print("  -", w)
    else:
        print("변경 없음 (이미 최신).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
